Debian latest: 'debian:latest'
Debian 13: 'debian:13'
Debian 12: 'debian:12'
Debian 11: 'debian:11'
Debian 10: 'debian:10'
Alpine latest: 'alpine:latest'
Alpine 3.24: 'alpine:3.24'
Alpine 3.23: 'alpine:3.23'
Alpine 3.22: 'alpine:3.22'
Alpine 3.21: 'alpine:3.21'
Scratch: 'scratch'