Ruby 2.7: ghcr.io/faithnode/pterodactyl-images/ruby:2.7
Ruby 3.0: ghcr.io/faithnode/pterodactyl-images/ruby:3.0
Ruby 3.1: ghcr.io/faithnode/pterodactyl-images/ruby:3.1
Ruby 3.2: ghcr.io/faithnode/pterodactyl-images/ruby:3.2
Ruby 3.3: ghcr.io/faithnode/pterodactyl-images/ruby:3.3
Ruby 3.4: ghcr.io/faithnode/pterodactyl-images/ruby:3.4