GO 1.15: ghcr.io/faithnode/pterodactyl-images/go:1.15
GO 1.16: ghcr.io/faithnode/pterodactyl-images/go:1.16
GO 1.17: ghcr.io/faithnode/pterodactyl-images/go:1.17
GO 1.18: ghcr.io/faithnode/pterodactyl-images/go:1.18
GO 1.19: ghcr.io/faithnode/pterodactyl-images/go:1.19
GO 1.20: ghcr.io/faithnode/pterodactyl-images/go:1.20
GO 1.21: ghcr.io/faithnode/pterodactyl-images/go:1.21
GO 1.22: ghcr.io/faithnode/pterodactyl-images/go:1.22
GO 1.23: ghcr.io/faithnode/pterodactyl-images/go:1.23
GO 1.24: ghcr.io/faithnode/pterodactyl-images/go:1.24
GO 1.25: ghcr.io/faithnode/pterodactyl-images/go:1.25
GO 1.26: ghcr.io/faithnode/pterodactyl-images/go:1.26
GO 1.27: ghcr.io/faithnode/pterodactyl-images/go:1.27