Java 25: 'ghcr.io/faithnode/pterodactyl-images/java:25'
Java 21: 'ghcr.io/faithnode/pterodactyl-images/java:21'
Java 8: 'ghcr.io/faithnode/pterodactyl-images/java:8'
Java 11: 'ghcr.io/faithnode/pterodactyl-images/java:11'
Java 15: 'ghcr.io/faithnode/pterodactyl-images/java:15'
Java 16: 'ghcr.io/faithnode/pterodactyl-images/java:16'
Java 17: 'ghcr.io/faithnode/pterodactyl-images/java:17'
Java 18: 'ghcr.io/faithnode/pterodactyl-images/java:18'
Java 19: 'ghcr.io/faithnode/pterodactyl-images/java:19'
Java 20: 'ghcr.io/faithnode/pterodactyl-images/java:20'
Java 22: 'ghcr.io/faithnode/pterodactyl-images/java:22'
Java 23: 'ghcr.io/faithnode/pterodactyl-images/java:23'
Java 24: 'ghcr.io/faithnode/pterodactyl-images/java:24'
