Python 2.7: ghcr.io/faithnode/pterodactyl-images/python:2.7
Python 3.6: ghcr.io/faithnode/pterodactyl-images/python:3.6
Python 3.7: ghcr.io/faithnode/pterodactyl-images/python:3.7
Python 3.8: ghcr.io/faithnode/pterodactyl-images/python:3.8
Python 3.9: ghcr.io/faithnode/pterodactyl-images/python:3.9
Python 3.10: ghcr.io/faithnode/pterodactyl-images/python:3.10
Python 3.11: ghcr.io/faithnode/pterodactyl-images/python:3.11
Python 3.12: ghcr.io/faithnode/pterodactyl-images/python:3.12
Python 3.13: ghcr.io/faithnode/pterodactyl-images/python:3.13
Python 3.14: ghcr.io/faithnode/pterodactyl-images/python:3.14