Dotnet 3.1: ghcr.io/faithnode/pterodactyl-images/dotnet:3.1
Dotnet 5.0: ghcr.io/faithnode/pterodactyl-images/dotnet:5.0
Dotnet 6.0: ghcr.io/faithnode/pterodactyl-images/dotnet:6.0
Dotnet 7.0: ghcr.io/faithnode/pterodactyl-images/dotnet:7.0
Dotnet 8.0: ghcr.io/faithnode/pterodactyl-images/dotnet:8.0
Dotnet 9.0: ghcr.io/faithnode/pterodactyl-images/dotnet:9.0
Dotnet 10.0: ghcr.io/faithnode/pterodactyl-images/dotnet:10.0