Rust 1.0: ghcr.io/faithnode/pterodactyl-images/rust:1
Rust 1.20: ghcr.io/faithnode/pterodactyl-images/rust:1.20
Rust 1.30: ghcr.io/faithnode/pterodactyl-images/rust:1.30
Rust 1.40: ghcr.io/faithnode/pterodactyl-images/rust:1.40
Rust 1.50: ghcr.io/faithnode/pterodactyl-images/rust:1.50
Rust 1.60: ghcr.io/faithnode/pterodactyl-images/rust:1.60
Rust 1.70: ghcr.io/faithnode/pterodactyl-images/rust:1.70
Rust 1.80: ghcr.io/faithnode/pterodactyl-images/rust:1.80
Rust 1.90: ghcr.io/faithnode/pterodactyl-images/rust:1.90