NodeJS 12: ghcr.io/faithnode/pterodactyl-images/nodejs:12
NodeJS 14: ghcr.io/faithnode/pterodactyl-images/nodejs:14
NodeJS 15: ghcr.io/faithnode/pterodactyl-images/nodejs:15
NodeJS 16: ghcr.io/faithnode/pterodactyl-images/nodejs:16
NodeJS 17: ghcr.io/faithnode/pterodactyl-images/nodejs:17
NodeJS 18: ghcr.io/faithnode/pterodactyl-images/nodejs:18
NodeJS 19: ghcr.io/faithnode/pterodactyl-images/nodejs:19
NodeJS 20: ghcr.io/faithnode/pterodactyl-images/nodejs:20
NodeJS 21: ghcr.io/faithnode/pterodactyl-images/nodejs:21
NodeJS 22: ghcr.io/faithnode/pterodactyl-images/nodejs:22
NodeJS 23: ghcr.io/faithnode/pterodactyl-images/nodejs:23
NodeJS 24: ghcr.io/faithnode/pterodactyl-images/nodejs:24
NodeJS 25: ghcr.io/faithnode/pterodactyl-images/nodejs:25
NodeJS 26: ghcr.io/faithnode/pterodactyl-images/nodejs:26
Bun 1.0: ghcr.io/faithnode/pterodactyl-images/bun:1.0
Bun 1.1: ghcr.io/faithnode/pterodactyl-images/bun:1.1
Bun 1.2: ghcr.io/faithnode/pterodactyl-images/bun:1.2
Bun 1.3: ghcr.io/faithnode/pterodactyl-images/bun:1.3
Bun 1.4: ghcr.io/faithnode/pterodactyl-images/bun:1.4