name: Test

on:
  push:
    paths:
      - eggs/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build toolbox image
        run: docker build -t pterodactyl-eggs-toolbox -f Dockerfile .

      - name: Build
        run: |
          docker run --rm -v "$PWD:/repo" -w /repo \
            pterodactyl-eggs-toolbox bin/build.sh

      - name: Test
        run: |
          docker run --rm -v "$PWD:/repo" -w /repo \
            -v /var/run/docker.sock:/var/run/docker.sock \
            pterodactyl-eggs-toolbox bin/test.sh
